### ISSUE TITLE
Replace deprecated AppCache with ServiceWorkers

### ISSUE THREAD

**Issue by troley** [eveoh/room-display#55]
**Important note**:
ServiceWorkers are still a [working draft](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker#Specifications), though all the browsers we support (and for each browser at least the 2 latest versions) seem to be supported by default. Nonetheless, most of the (if not all) features of the ServiceWorker and related API's ([Cache](https://developer.mozilla.org/en-US/docs/Web/API/Cache), [CacheStorage](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage) etc.) are experimental and their behavior might change in the future.

## Description

In order to have a modern, not deprecated offline caching mechanism, Room Display should replace the currently used [Application Cache (AppCache)](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) with the [ServiceWorker](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker)s.

## Origin and motivation

The application is caching content for offline usage by using HTML manifest AppCache. In our case this is the `manifest.appcache` file that is being used in the HTML: `<html manifest="manifest.appcache">`. 

This feature is deprecated since Firefox 44+ and is in the process of being [removed](https://html.spec.whatwg.org/multipage/offline.html#offline) from the web platform. It is recommended to move to a modern approach for offline content caching with the ServiceWorker and the related [ServiceWorker API](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API).

## Subtasks
- [ ] Investigate how the ServiceWorkers can be used for content caching
- [ ] Identify potential important differences between the AppCache and the ServiceWorkers
- [ ] Create a sample PR which showcases ServiceWorkers in action
- [ ] Replace the deprecated AppCache with ServiceWorkers completely

## Acceptance criteria

- [ ] AppCache has been replaced by ServiceWorkers.

**Comment by marcokrikke** [comment]
Ik heb hier blijkbaar ooit eens mee lopen rommelen. Zie wat code hieronder, geen idee of het werkt. Belangrijk is om in ieder geval de appcache eerst te verwijderen en dat aan je browser te leren, anders gaat het door elkaar werken. 

`service-worker.js`:

````js
const cacheVersion = '@timestamp@';

self.addEventListener('install', (event) => {
    // Force immediate activation
    self.skipWaiting();

    // Cache all required assets
    event.waitUntil(async function () {
        const cache = await caches.open(cacheVersion);

        await cache.addAll([
            '/',
            '/config.json',
            '/css/style.css',
            '/error/index.html',
            '/index.html',
            '/js/app.js',
            '/provision/index.html',
            '/settings/index.html',
            'images/favicon.ico',
            'images/favicon-60px.png',
            'images/favicon-76px.png',
            'images/favicon-120px.png',
            'images/favicon-152px.png',
            'images/favicon-180px.png'
        ]);
    }());
});

self.addEventListener('activate', (event) => {
    event.waitUntil(async function () {
        // Remove old caches
        const cacheNames = await caches.keys();

        await Promise.all(
            cacheNames.filter((cacheName) => {
                return cacheName !== cacheVersion;
            }).map(cacheName => caches.delete(cacheName))
        );

        // Claim the service work for this client
        await self.clients.claim();
    }());
});

    // return self.clients.claim();

self.addEventListener('fetch', (event) => {
    // Return response for cache. Otherwise, fallback to network.
    event.respondWith(async function() {
        const response = await caches.match(event.request);

        return response || fetch(event.request);
    }());
});
````

`updater.js` fragment:

````js
app.eventBus.on("app:start", function() {
    // Register the service worker to cache assets for offline usage
    if ('serviceWorker' in navigator) {
        navigator.serviceWorker.register('service-worker.js')
            .then(function (registration) {
                if (registration.active) {
                    console.log('Service Worker activated with scope: ' + registration.scope);
                }

                registration.addEventListener('updatefound', () => {
                    const newServiceWorker = registration.installing;

                    newServiceWorker.addEventListener('statechange', () => {
                        if (newServiceWorker.state === 'activated') {
                            console.log("New Service Worker activated. Reloading page.");

                            app.updater.onUpdateReady();
                        }
                    });
                });

                // Set a repeating timer which checks for service worker updates.
                setInterval(() =>  {
                    console.log("Checking for new Service Worker");

                    registration.update().catch(function (error) {
                        console.log('Update failed with ' + error);
                    });
                }, app.config.updateCheckInterval * 1000);
            }).catch(function (error) {
            // registration failed
            console.log('Registration failed with ' + error);
        });
    }

    // Set a repeating timer which checks for application configuration updates.
    setInterval(() => {
        app.updater.check();
    }, app.config.updateCheckInterval * 1000);
});
````
